"""add link matching

Revision ID: cd57e7207a27
Revises: 6368550a623f
Create Date: 2026-10-07 14:32:22.406369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd57e7207a27'
down_revision = '6368550a623f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('url_a', sa.String(), nullable=False),
    sa.Column('url_b', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('normalized_link', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('target_chat_id', sa.BigInteger(), nullable=True))

    # fill in the cleaned link for reports that were saved before this column existed
    from url_utils import normalize_url
    connection = op.get_bind()
    projects = sa.table('projects',
                        sa.column('id', sa.Integer),
                        sa.column('group_link', sa.String),
                        sa.column('normalized_link', sa.String))
    rows = connection.execute(sa.select(projects.c.id, projects.c.group_link)).fetchall()
    for row_id, group_link in rows:
        connection.execute(
            projects.update().where(projects.c.id == row_id)
            .values(normalized_link=normalize_url(group_link) or group_link)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('target_chat_id')
        batch_op.drop_column('normalized_link')

    op.drop_table('link_alias')
    # ### end Alembic commands ###
